/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI.eventFrames;

import event.*;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import location.*;
import javax.swing.JOptionPane;
/**
 *
 * @author stive
 */
public class CreateEvent extends javax.swing.JFrame {
    LocationManager locationManager = new LocationManager(states.AppState.locationsList); 
    /**
     * Creates new form CreateEvent
     */
    public CreateEvent() {
        initComponents();
        locationManager.locationListBox(eventLocationSelect);
        
        eventType.removeAllItems();
        eventType.addItem("Concert");
        eventType.addItem("Conference");
        eventType.addItem("Stand Up");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        eventName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        eventDate = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        eventLocationSelect = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        eventDesc = new javax.swing.JTextField();
        btnCreateEvent = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        eventType = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(542, 498));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Event details");

        jLabel2.setText("Name");

        jLabel3.setText("Event Date (yyyy-MM-dd HH:mm)");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Create Event Screen");

        jLabel5.setText("Location");

        eventLocationSelect.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel6.setText("Description");

        btnCreateEvent.setBackground(new java.awt.Color(0, 153, 102));
        btnCreateEvent.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCreateEvent.setForeground(new java.awt.Color(255, 255, 255));
        btnCreateEvent.setText("Register event");
        btnCreateEvent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateEventActionPerformed(evt);
            }
        });

        jLabel7.setText("Event Type");

        eventType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCreateEvent)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(eventName)
                    .addComponent(jLabel3)
                    .addComponent(eventDate)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(eventLocationSelect, 0, 485, Short.MAX_VALUE)
                    .addComponent(jLabel6)
                    .addComponent(eventDesc)
                    .addComponent(jLabel7)
                    .addComponent(eventType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(eventName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(eventDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(eventLocationSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(eventDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(eventType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(btnCreateEvent)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateEventActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateEventActionPerformed
        try {
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm");
            LocalDateTime date = LocalDateTime.parse(eventDate.getText(), formatter);

            if (eventLocationSelect.getSelectedItem() == null || eventLocationSelect.getSelectedItem() == "") {
                JOptionPane.showMessageDialog(this, "[ERROR] The location cannot be null!");
            }

            String locIdText = (String) eventLocationSelect.getSelectedItem();
            int locationId = Integer.parseInt(locIdText.split(" ")[0]);
            Location locationSelected = locationManager.getLocationById(locationId);
            if (eventType.getSelectedItem() == "Concert") {
                ConcertEvent concert = new ConcertEvent(eventName.getText(), date, locationSelected, eventDesc.getText());
                states.AppState.eventList.add(concert);
            } else if (eventType.getSelectedItem() == "Conference") {
                ConferenceEvent conference = new ConferenceEvent(eventName.getText(), date, locationSelected, eventDesc.getText());
                states.AppState.eventList.add(conference);
            } else {
                StandUpEvent standUp = new StandUpEvent(eventName.getText(), date, locationSelected, eventDesc.getText());
                states.AppState.eventList.add(standUp);
            }
            locationManager.deleteAvailableDate(date.toLocalDate(), locationSelected);
            JOptionPane.showMessageDialog(this, "Registered Event!");
        } catch (java.lang.NullPointerException e) {
            JOptionPane.showMessageDialog(this, "[ERROR]" + " The location cannot be null!", "error", JOptionPane.ERROR_MESSAGE);
        } catch (java.time.format.DateTimeParseException e) {            
            JOptionPane.showMessageDialog(this, "[ERROR]" + " Invalid date!", "error", JOptionPane.ERROR_MESSAGE);            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "[ERROR]" + e.getMessage(), "error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnCreateEventActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateEvent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateEvent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateEvent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateEvent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateEvent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateEvent;
    private javax.swing.JTextField eventDate;
    private javax.swing.JTextField eventDesc;
    private javax.swing.JComboBox<String> eventLocationSelect;
    private javax.swing.JTextField eventName;
    private javax.swing.JComboBox<String> eventType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
