/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import GUI.artistFrames.*;

/**
 *
 * @author soporte.agente2
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        mainMenu = new javax.swing.JMenuBar();
        locationManagement = new javax.swing.JMenu();
        eventManagement = new javax.swing.JMenu();
        participantManagement = new javax.swing.JMenu();
        registerArtist = new javax.swing.JMenuItem();
        showArtists = new javax.swing.JMenuItem();
        artistHistory = new javax.swing.JMenuItem();
        ticketManagement = new javax.swing.JMenu();
        accessControl = new javax.swing.JMenu();
        financialManagement = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("EventMaster Pro");
        setPreferredSize(new java.awt.Dimension(800, 450));
        setResizable(false);
        setSize(new java.awt.Dimension(800, 450));

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 36)); // NOI18N
        jLabel1.setText("EventMaster Pro");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel2.setText("Manage Your Event");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Main Screen");

        mainMenu.setBackground(new java.awt.Color(0, 153, 102));
        mainMenu.setForeground(new java.awt.Color(0, 0, 0));

        locationManagement.setForeground(new java.awt.Color(255, 255, 255));
        locationManagement.setText("Locations Management");
        mainMenu.add(locationManagement);

        eventManagement.setForeground(new java.awt.Color(255, 255, 255));
        eventManagement.setText("Events Management");
        mainMenu.add(eventManagement);

        participantManagement.setForeground(new java.awt.Color(255, 255, 255));
        participantManagement.setText("Participant Management");

        registerArtist.setText("Register an artist");
        registerArtist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerArtistActionPerformed(evt);
            }
        });
        participantManagement.add(registerArtist);

        showArtists.setText("Show all artists");
        showArtists.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showArtistsActionPerformed(evt);
            }
        });
        participantManagement.add(showArtists);

        artistHistory.setText("Artist history");
        artistHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                artistHistoryActionPerformed(evt);
            }
        });
        participantManagement.add(artistHistory);

        mainMenu.add(participantManagement);

        ticketManagement.setForeground(new java.awt.Color(255, 255, 255));
        ticketManagement.setText("Ticket Management");
        mainMenu.add(ticketManagement);

        accessControl.setForeground(new java.awt.Color(255, 255, 255));
        accessControl.setText("Access Control");
        mainMenu.add(accessControl);

        financialManagement.setForeground(new java.awt.Color(255, 255, 255));
        financialManagement.setText("Financial Management");
        mainMenu.add(financialManagement);

        setJMenuBar(mainMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(250, 250, 250))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(317, 317, 317)
                        .addComponent(jLabel2)))
                .addGap(328, 328, 328))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 179, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registerArtistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerArtistActionPerformed
        ArtistRegistration artistRegistration =  new ArtistRegistration();
        artistRegistration.setLocationRelativeTo(null);
        artistRegistration.setVisible(true);
    }//GEN-LAST:event_registerArtistActionPerformed

    private void showArtistsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showArtistsActionPerformed
        ShowAllArtist showAllArtist =  new ShowAllArtist();
        showAllArtist.setLocationRelativeTo(null);
        showAllArtist.setVisible(true);
    }//GEN-LAST:event_showArtistsActionPerformed

    private void artistHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_artistHistoryActionPerformed
        ArtistHistory artistsHistory = new ArtistHistory();
        artistsHistory.setLocationRelativeTo(null);
        artistsHistory.setVisible(true);
    }//GEN-LAST:event_artistHistoryActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu accessControl;
    private javax.swing.JMenuItem artistHistory;
    private javax.swing.JMenu eventManagement;
    private javax.swing.JMenu financialManagement;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu locationManagement;
    private javax.swing.JMenuBar mainMenu;
    private javax.swing.JMenu participantManagement;
    private javax.swing.JMenuItem registerArtist;
    private javax.swing.JMenuItem showArtists;
    private javax.swing.JMenu ticketManagement;
    // End of variables declaration//GEN-END:variables
}
