package GUI.artistFrames;

import artist.*;
import event.*;
import javax.swing.JOptionPane;

public class ArtistRegistration extends javax.swing.JFrame {

    /**
     * Creates new form ArtistRegistration
     */
    public ArtistRegistration() {
        initComponents();
        TypeArtist typeArtist = new TypeArtist();
        typeArtist.categoryListBox(typeArtistSelection);
                
        EventManager eventManager = new EventManager(states.AppState.eventList);                
        eventManager.eventListBox(artistHistorySelection);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtName = new javax.swing.JLabel();
        artistName = new javax.swing.JTextField();
        txtDescription = new javax.swing.JLabel();
        artistDescription = new javax.swing.JTextField();
        txtContact = new javax.swing.JLabel();
        artistContact = new javax.swing.JTextField();
        txtType = new javax.swing.JLabel();
        typeArtistSelection = new javax.swing.JComboBox<>();
        txtHistory = new javax.swing.JLabel();
        artistHistorySelection = new javax.swing.JComboBox<>();
        btnRegisterArtist = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(500, 450));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Artist Register Screen");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Artist details");

        txtName.setText("Name");

        artistName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                artistNameActionPerformed(evt);
            }
        });

        txtDescription.setText("Description");

        txtContact.setText("Contact");

        txtType.setText("Select the type of artist");

        typeArtistSelection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeArtistSelectionActionPerformed(evt);
            }
        });

        txtHistory.setText("Add event to artist's history");

        btnRegisterArtist.setBackground(new java.awt.Color(0, 153, 102));
        btnRegisterArtist.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRegisterArtist.setForeground(new java.awt.Color(255, 255, 255));
        btnRegisterArtist.setText("Register artist");
        btnRegisterArtist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterArtistActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnRegisterArtist)
                    .addComponent(txtHistory)
                    .addComponent(txtType)
                    .addComponent(txtContact)
                    .addComponent(txtDescription)
                    .addComponent(jLabel3)
                    .addComponent(txtName)
                    .addComponent(jLabel1)
                    .addComponent(artistName)
                    .addComponent(artistDescription)
                    .addComponent(artistContact)
                    .addComponent(typeArtistSelection, 0, 400, Short.MAX_VALUE)
                    .addComponent(artistHistorySelection, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(artistName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDescription)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(artistDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtContact)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(artistContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtType)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(typeArtistSelection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtHistory)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(artistHistorySelection, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(btnRegisterArtist)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void artistNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_artistNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_artistNameActionPerformed

    private void typeArtistSelectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeArtistSelectionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_typeArtistSelectionActionPerformed

    private void btnRegisterArtistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterArtistActionPerformed
        try {
            Artist artist = new Artist();            
            artist.register(artistName.getText(), artistDescription.getText(), artistContact.getText(), (String) artistHistorySelection.getSelectedItem(), (String) typeArtistSelection.getSelectedItem());
            JOptionPane.showMessageDialog(this, "Registered artist!");
        } catch (Exception e) {            
            JOptionPane.showMessageDialog(this, "[ERROR]" + e.getMessage(), "error", JOptionPane.ERROR_MESSAGE);            
        }
    }//GEN-LAST:event_btnRegisterArtistActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ArtistRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ArtistRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ArtistRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ArtistRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ArtistRegistration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField artistContact;
    private javax.swing.JTextField artistDescription;
    private javax.swing.JComboBox<String> artistHistorySelection;
    private javax.swing.JTextField artistName;
    private javax.swing.JButton btnRegisterArtist;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel txtContact;
    private javax.swing.JLabel txtDescription;
    private javax.swing.JLabel txtHistory;
    private javax.swing.JLabel txtName;
    private javax.swing.JLabel txtType;
    private javax.swing.JComboBox<String> typeArtistSelection;
    // End of variables declaration//GEN-END:variables
}
