/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI.locationsFrames;

import java.time.LocalDate;
import javax.swing.JOptionPane;
import location.*;

/**
 *
 * @author stive
 */
public class AddAvailableDateLocation extends javax.swing.JFrame {
    LocationManager locationManager = new LocationManager(states.AppState.locationsList); 
    /**
     * Creates new form AddAvailableDateLocation
     */
    public AddAvailableDateLocation() {
        initComponents();
        locationManager.locationListBox(locationSelect);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        idTxt = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        newDate = new javax.swing.JTextField();
        btnAddDate = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        locationSelect = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(534, 350));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Location details");

        idTxt.setText("Location");

        jLabel2.setText("New Available Date (yyyy-MM-dd)");

        newDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newDateActionPerformed(evt);
            }
        });

        btnAddDate.setBackground(new java.awt.Color(0, 153, 102));
        btnAddDate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAddDate.setForeground(new java.awt.Color(255, 255, 255));
        btnAddDate.setText("Add available date");
        btnAddDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddDateActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Add Available Date To Location Screen");

        locationSelect.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        locationSelect.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                locationSelectKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAddDate)
                    .addComponent(jLabel1)
                    .addComponent(idTxt)
                    .addComponent(jLabel2)
                    .addComponent(newDate, javax.swing.GroupLayout.DEFAULT_SIZE, 485, Short.MAX_VALUE)
                    .addComponent(jLabel3)
                    .addComponent(locationSelect, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(idTxt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(locationSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(btnAddDate)
                .addGap(27, 27, 27)
                .addComponent(jLabel3)
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newDateActionPerformed

    private void btnAddDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddDateActionPerformed
        try {
            String locIdText = (String) locationSelect.getSelectedItem();
            int locationId = Integer.parseInt(locIdText.split(" ")[0]);
            Location locationSelected = locationManager.getLocationById(locationId);
            if (locationSelected != null) {
                locationSelected.addAvailableDate(LocalDate.parse(newDate.getText()));
                JOptionPane.showMessageDialog(this, "Available date added successfully!");
            } else {
                JOptionPane.showMessageDialog(this, "The location was not found!");
            }
        } catch (java.lang.NullPointerException e) {
            JOptionPane.showMessageDialog(this, "[ERROR]" + " The location cannot be null!", "error", JOptionPane.ERROR_MESSAGE);
        } catch (java.time.format.DateTimeParseException e) {            
            JOptionPane.showMessageDialog(this, "[ERROR]" + " Invalid date!", "error", JOptionPane.ERROR_MESSAGE);            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "[ERROR]" + e.getMessage(), "error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAddDateActionPerformed

    private void locationSelectKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_locationSelectKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_locationSelectKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddAvailableDateLocation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddAvailableDateLocation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddAvailableDateLocation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddAvailableDateLocation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddAvailableDateLocation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddDate;
    private javax.swing.JLabel idTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JComboBox<String> locationSelect;
    private javax.swing.JTextField newDate;
    // End of variables declaration//GEN-END:variables
}
