/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI.locationsFrames;

import java.time.LocalDate;
import javax.swing.JOptionPane;
import location.*;

public class CreateLocation extends javax.swing.JFrame {

    /**
     * Creates new form CreateLocation
     */
    public CreateLocation() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TitleFrame = new javax.swing.JLabel();
        txtName = new javax.swing.JLabel();
        locationName = new javax.swing.JTextField();
        txtAddress = new javax.swing.JLabel();
        locationAddress = new javax.swing.JTextField();
        txtCapacity = new javax.swing.JLabel();
        txtTechSpec = new javax.swing.JLabel();
        locationTechSpec = new javax.swing.JTextField();
        btnRegisterLocation = new javax.swing.JButton();
        FooterTxt = new javax.swing.JLabel();
        locationCapacity = new javax.swing.JTextField();
        txtDate = new javax.swing.JLabel();
        locationDate = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(542, 473));

        TitleFrame.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TitleFrame.setText("Location details");

        txtName.setText("Name");

        txtAddress.setText("Address");

        locationAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                locationAddressActionPerformed(evt);
            }
        });

        txtCapacity.setText("Capacity");

        txtTechSpec.setText("Technical Specifications");

        btnRegisterLocation.setBackground(new java.awt.Color(0, 153, 102));
        btnRegisterLocation.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRegisterLocation.setForeground(new java.awt.Color(255, 255, 255));
        btnRegisterLocation.setText("Register location");
        btnRegisterLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterLocationActionPerformed(evt);
            }
        });

        FooterTxt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        FooterTxt.setText("Create Location Screen");

        locationCapacity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                locationCapacityKeyTyped(evt);
            }
        });

        txtDate.setText("Initial Available Date (yyyy-MM-dd)");

        locationDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                locationDateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnRegisterLocation)
                    .addComponent(locationTechSpec)
                    .addComponent(txtAddress)
                    .addComponent(txtCapacity)
                    .addComponent(locationAddress)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TitleFrame)
                    .addComponent(txtTechSpec)
                    .addComponent(FooterTxt)
                    .addComponent(locationCapacity)
                    .addComponent(txtDate)
                    .addComponent(locationDate, javax.swing.GroupLayout.DEFAULT_SIZE, 485, Short.MAX_VALUE)
                    .addComponent(locationName))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(TitleFrame)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(locationName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtAddress)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(locationAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtCapacity)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(locationCapacity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtTechSpec)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(locationTechSpec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtDate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(locationDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(btnRegisterLocation)
                .addGap(18, 18, 18)
                .addComponent(FooterTxt)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void locationAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_locationAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_locationAddressActionPerformed

    private void btnRegisterLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterLocationActionPerformed
        try {
            Location location = new Location(locationName.getText(), locationAddress.getText(), Integer.parseInt(locationCapacity.getText()), locationTechSpec.getText(), LocalDate.parse(locationDate.getText()));
            states.AppState.locationsList.add(location);
            JOptionPane.showMessageDialog(this, "Registered Location!");
        } catch (java.time.format.DateTimeParseException e) {            
            JOptionPane.showMessageDialog(this, "[ERROR]" + " Invalid date!", "error", JOptionPane.ERROR_MESSAGE);            
        } catch (java.lang.NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "[ERROR]" + " The capacity atribute is empty!", "error", JOptionPane.ERROR_MESSAGE);  
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "[ERROR]" + e.getMessage(), "error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnRegisterLocationActionPerformed

    private void locationCapacityKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_locationCapacityKeyTyped
        char key = evt.getKeyChar();
        if (!Character.isDigit(key)) {
            evt.consume();
        }
    }//GEN-LAST:event_locationCapacityKeyTyped

    private void locationDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_locationDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_locationDateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateLocation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateLocation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateLocation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateLocation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateLocation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FooterTxt;
    private javax.swing.JLabel TitleFrame;
    private javax.swing.JButton btnRegisterLocation;
    private javax.swing.JTextField locationAddress;
    private javax.swing.JTextField locationCapacity;
    private javax.swing.JTextField locationDate;
    private javax.swing.JTextField locationName;
    private javax.swing.JTextField locationTechSpec;
    private javax.swing.JLabel txtAddress;
    private javax.swing.JLabel txtCapacity;
    private javax.swing.JLabel txtDate;
    private javax.swing.JLabel txtName;
    private javax.swing.JLabel txtTechSpec;
    // End of variables declaration//GEN-END:variables
}
